encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.wiki, name="wiki"),
    path("new", views.new, name="new"),
    path("search/", views.search, name="search"),
    path("edit/<str:entry>", views.edit, name="edit"),
    path("random", views.random_entry, name="random_entry")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('encyclopedia/', include('encyclopedia.urls', namespace='encyclopedia')),
    path('admin/', admin.site.urls),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, Http404
from . import util
from django import forms
from random import randint
import re
from django.contrib import messages
from markdown2 import Markdown


class NewEntryForm(forms.Form):
    title = forms.CharField(
        required=True,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Title", "class": "mb-4"}
        ),
    )
    content = forms.CharField(
        required=True,
        label="",
        widget= forms.Textarea(
            attrs={
                "class": "form-control mb-4",
                "placeholder": "Content (markdown)",
                "id": "new_content",
            }
        ),
    )

def index(request):
    return render(
        request, "encyclopedia/index.html", {"entries": util.list_entries()}
    )

def wiki(request, entry):
    if entry not in util.list_entries():
        raise Http404
    content = util.get_entry(entry)
    return render(
        request,
        "encyclopedia/wiki.html",
        {"title": entry, "content": Markdown().convert(content)},
    )

def search(request):
    entries = util.list_entries()
    query = request.session['query']
    find_entries = list()

    search_box = request.POST.get("q", "").capitalize()

    if search_box in entries:
        return HttpResponseRedirect(f"wiki/{search_box}")

    for entry in entries:
        if re.search(query, entry):
            find_entries.append(entry)

    if find_entries:
        return render(request, "encyclopedia/search.html", {
            "search_result": find_entries,
            "search": search_box
        })

def new(request):
    if request.method == "GET":
        return render(
            request, "encyclopedia/new.html", {"form": NewEntryForm()}
        )

    form = NewEntryForm(request.POST)
    if form.is_valid():
        title = form.cleaned_data.get("title")
        content = form.cleaned_data.get("content")

        if title.lower() in [entry.lower() for entry in util.list_entries()]:
            messages.add_message(
                request,
                messages.WARNING,
                message=f'Entry "{title}" already exists',
            )
        else:
            with open(f"entries/{title}.md", "w") as file:
                file.write(content)
            return redirect("encyclodepia:wiki", title)

    else:
        messages.add_message(
            request, messages.WARNING, message="Invalid request form"
        )

    return render(
        request,
        "encyclopedia/new.html",
        {"form": form},
    )

def random_entry(request):
    entries = util.list_entries()
    entry = entries[randint(0, len(entries) - 1)]
    return redirect("encyclopedia:wiki", entry)

def edit(request, entry):
    if request.method == "GET":
        title = entry
        content = util.get_entry(title)
        form = NewEntryForm({"title": title, "content": content})
        return render(
            request,
            "encyclopedia/edit.html",
            {"form": form, "title": title},
        )

    form = NewEntryForm(request.POST)
    if form.is_valid():
        title = form.cleaned_data.get("title")
        content = form.cleaned_data.get("content")

        util.save_entry(title=title, content=content)
        return redirect("encyclopedia:wiki", title)

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Edit | {{ title }} | Encyclopedia
{% endblock %}

{% block body %}

    <form action="{% url 'encyclopedia:edit' title %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form }}
            <button class="btn btn-primary" type="submit">Save</button>
        </div>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
        <li><a href="{% url 'encyclopedia:wiki' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>

<body>
    <div class="row">
        <div class="sidebar col-lg-2 col-md-3">
            <h2>Wiki</h2>
            <form action="{% url 'encyclopedia:search' %}">
                <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
            </form>
            <div>
                <a href="{% url 'encyclopedia:index' %}">Home</a>
            </div>
            <div>
                <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div class="main col-lg-10 col-md-9">
            {% block body %}
            {% endblock %}
        </div>
    </div>

</body>

</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
New | Encyclopedia
{% endblock %}

{% block body %}

{% if messages %}

{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert">{{ message }}</div>
{% endfor %}

{% endif %}

    <form action="{% url 'encyclopedia:new' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form }}
            <button class="btn btn-primary" type="submit">Create new entry</button>
        </div>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Search | Encyclopedia
{% endblock %}

{% block body %}

{% if found_entries %}
    <h2>Results for "{{ query }}"</h2>
    <ul>
        {% for entry in found_entries %}
        <li><a href="{% url 'encycloepedia:wiki' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <h2>No entries found for "{{ query }}"</h2>
{% endif %}

{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ title }} | Encyclopedia
{% endblock %}

{% block body %}
{{ content|safe }}
<br>Something wrong? <a href="{% url 'encyclopedia:edit' title %}">Edit</a> this page!
{% endblock %}